//
//  IBError.swift
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the DVStarterProject Xcode Templates,
//  see http://technaharia.in
//  Credit: Dinesh Saini, Varun Naharia

import Foundation

class IBError : NSObject{
    
    var requestID  : String = ""
    var requestUrl  : String = ""
    var errorCode   : String = ""
    var message     : String = ""
    var userInfo    = [String : Any]()
    
}
